# Generated by Django 4.2.2 on 2023-06-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancodedados', '0003_relatoriocompra_relatoriovenda_venda_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='produto',
        ),
        migrations.DeleteModel(
            name='RelatorioCompra',
        ),
        migrations.DeleteModel(
            name='RelatorioVenda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.produto'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='corredor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.corredor'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='prateleira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.prateleira'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancodedados.setor'),
        ),
    ]
